### カテゴリ一覧取得
GET http://localhost:8080/api/categories

### 商品一覧取得
GET http://localhost:8080/api/products


### 商品詳細取得
GET http://localhost:8080/api/products/3


### カテゴリ別の商品一覧取得

GET http://localhost:8080/api/products/category/1

GET http://localhost:8080/api/products/category/2




### カートに追加
POST http://localhost:8080/api/cart
content-type: application/json

{
    "productId": 1, 
    "quantity": 2
}